# Site settings
title: lighthouse.log
description: Ideas worth spreading.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://lighthouse-dev.github.io" # the base hostname & protocol for your site e.g. http://willianjusten.com.br
google_analytics:
  ua: 'UA-105814287-1'

# User settings
username: lighthouse-dev
user_description: Juseung Lee
user_title: full stack developer
email: lighthouse2.dev@gmail.com
twitter_username: 
github_username:  lighthouse-dev
gplus_username:  
disqus_username: 

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: Categories
    url: /categories
  - title: Tags
    url: /tags
  - title: About Me
    url: /about

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
